# Generated by Django 4.0.5 on 2022-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test123', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=50)),
                ('search_word', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
