# Generated by Django 4.0.5 on 2022-06-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test123', '0002_news_data_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='search_word',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField()),
                ('user_name', models.CharField(max_length=50, verbose_name='user')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test123.news_data')),
            ],
        ),
    ]
