# Generated by Django 4.0.5 on 2022-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test123', '0003_alter_news_data_search_word_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
