# Generated by Django 4.0.5 on 2022-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test123', '0004_alter_favourite_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='favourite',
            field=models.BooleanField(default=True),
        ),
    ]
